{% set name = "gulp" %}
{% set version = "4.0.1" %}
{% set sha256 = "3a59de60f5bebeb6495409f4c5887a1a00080ed4d6fd944909af074ff5ce394c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/gulpjs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: 
    - npm install -g gulp
 
requirements:
  build:
    - nodejs
  run:
    - nodejs
       
test:
  files:
    - gulpfile.js
  commands:
    - npm list -g gulp
    - npm link gulp && gulp

about:
  home: https://github.com/gulpjs/gulp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'The streaming build system'
  description: |
    The streaming build system
  doc_url: https://www.npmjs.com/package/gulp-documentation
  dev_url: hhttps://github.com/gulpjs/gulp

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
