{% set name = "gulp" %}
{% set version = "4.0.0" %}
{% set sha256 = "162ca655c3fe251d773da3ab4c4b4501a4fc7323576c0064cda7b5c06f0636d8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/gulpjs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: 
    - npm install -g gulp
 
requirements:
  build:
    - nodejs
  run:
    - nodejs
       
test:
  files:
    - gulpfile.js
  commands:
    - npm list -g gulp
    - npm link gulp && gulp

about:
  home: https://github.com/gulpjs/gulp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'The streaming build system'
  description: |
    The streaming build system
  doc_url: https://www.npmjs.com/package/gulp-documentation
  dev_url: hhttps://github.com/gulpjs/gulp

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
