travis:
  secure:
    BINSTAR_TOKEN: EEApujRKWVa3fMqcJm26A2RNtb5C+kVzQmX9l9LMLrpKSDN0pfq2GUYo4TemJg8jCMUSLtiJd+ZWPP1ASj8jkFX+dKGwbtw0Xkff+Cm/DcBApa/4mHXmAplV2vodCcmQSGQ5OK0x3X626wEW8Orahq+qXNOONREAqVfikI+EpwrkspKQyL4CUyJocFnlKTLoBGoQVJdp1ItcMtuWO+4DDY/HiWe467mKaTdWxKPzhscr28NsQLKfl2t+PIs8AIABlCX814svAjG+1J99tQtskBZ+qLnWH5b5aWQygsrxYy9oL9pb2n3Zs9mAm+/R8yB8BBjkcm/i/hp5hBjQ4utis6S7BfqRPeotC3H10EE1tlXaWfD0zkvW6ntIMJMqkPzZhx+cQZhC0qtX0eldKnKWLbLyWJkwUC+T14kA9w671gWhrV9isJjeSIUCBRdqlGie+BgIY0JiH5Qu4FUhGMk0jhR2PwEVvAqNfkbIRXDSCPTst/YpInqMTeAda0GV0mxtnMGMPdKbMCKiVz/5P8sM6Z0Tb28uYoe5upSLQbP+dd0PppxnPFU+CP5dXVLOAo8SvUdIvqDwKTwf8AZDo8THwNTV45iaimQ74i3fExq/Re0t6RhxRa3ShSQoxwitOntXH1vmOul+N8FDAmSzb588furi9Um8SYWtZEjX9D5qPgk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
