travis:
  secure:
    BINSTAR_TOKEN: kfMqt2IP81SKmkKFf8UTwLW9grc2FJQwlmFFjxLm0+IhH1GfANIoK0FTkMPzbLexZR0drRV16jQ0V7t0qzhZZ9hB2If1+T/2J15oY0TDh5KwmRIhkKqgQ4Ijut0qozJsWIqLdnGwjSX7FnfAuIPA7MNGtiIPqyn5nM26yj9glhTH9EEeONXTc+grQgQ4CFHXqfe9tAPPjlphMEh0xYKv+hjPxWXgxaoBz+gFojeG+d/osdo71czmwDNttEHpBWGHkR3Yofa6wX3kfw4DJnAz/RrxY9tM4z4VLrvKDr12kZXbw4TpY0jzrpUMXJl6rZtmtpnYQOodjh8Z4ThBE7gkv2tMl+kJuuSrUover0AIUI2nt09NE7Dy7RihIVo6fmS085yN5V1BMsqdaozeEw8WbVkzDJd97m444BFUHU4IP7jl0+AyYgBxlmh/+1ks7/Ke9dL4TUFGFO8be8NCe/BpPVD8EPVcLfNvotjP59b1y+c1X/bo9Yyr5e4w7e8+1PnzIr4xxo7GilOk7z3zwbIPsvg6ELLmsT3QkGeZ9t2KGW6X7MAgJgo3x7f+lnx3mc96JfECNsevc/jgFt/fJ0e2OXzXhKlpH6hWtYZ+4GsNFkrEx4NEwRzNw/u5i2j9gB37beJhyv3pUjGkUeXX3KL9U5HE1oGCTV/oqu6HaAlbYYQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
